/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Boilerplate API
 * API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List users
 */
export const usersControllerFindAllV1QueryPageDefault = 1;

export const usersControllerFindAllV1QueryPerPageDefault = 5;
export const usersControllerFindAllV1QueryPerPageMax = 100;

export const usersControllerFindAllV1QuerySearchMax = 255;



export const UsersControllerFindAllV1QueryParams = zod.object({
  "page": zod.number().min(1).default(usersControllerFindAllV1QueryPageDefault),
  "perPage": zod.number().min(1).max(usersControllerFindAllV1QueryPerPageMax).default(usersControllerFindAllV1QueryPerPageDefault),
  "search": zod.string().max(usersControllerFindAllV1QuerySearchMax).optional().describe('Filter by name or email (partial match)'),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']).optional(),
  "roleUuid": zod.uuid().optional().describe('Filter by an assigned role UUID')
})

export const usersControllerFindAllV1ResponseOneMetaOneTotalDefault = 0;
export const usersControllerFindAllV1ResponseOneMetaOnePageDefault = 1;
export const usersControllerFindAllV1ResponseOneMetaOnePerPageDefault = 5;
export const usersControllerFindAllV1ResponseOneMetaOneLastPageDefault = 1;
export const usersControllerFindAllV1ResponseOneMetaDefault = { "total": 0, "page": 1, "perPage": 5, "lastPage": 1 };

export const UsersControllerFindAllV1Response = zod.object({
  "meta": zod.object({
  "total": zod.number().default(usersControllerFindAllV1ResponseOneMetaOneTotalDefault),
  "page": zod.number().default(usersControllerFindAllV1ResponseOneMetaOnePageDefault),
  "perPage": zod.number().default(usersControllerFindAllV1ResponseOneMetaOnePerPageDefault),
  "lastPage": zod.number().default(usersControllerFindAllV1ResponseOneMetaOneLastPageDefault)
}).default(usersControllerFindAllV1ResponseOneMetaDefault)
}).and(zod.object({
  "data": zod.array(zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})).optional()
}))

/**
 * @summary Create a new user
 */
export const usersControllerCreateV1BodyEmailMax = 255;

export const usersControllerCreateV1BodyNameMax = 255;

export const usersControllerCreateV1BodyPasswordMin = 8;



export const UsersControllerCreateV1Body = zod.object({
  "email": zod.email().max(usersControllerCreateV1BodyEmailMax),
  "name": zod.string().max(usersControllerCreateV1BodyNameMax),
  "password": zod.string().min(usersControllerCreateV1BodyPasswordMin),
  "avatarUrl": zod.url().optional(),
  "roleUuids": zod.array(zod.uuid()).optional().describe('Role UUIDs to assign to the user')
})

export const UsersControllerCreateV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Get user by UUID
 */
export const UsersControllerFindOneV1Params = zod.object({
  "uuid": zod.string()
})

export const UsersControllerFindOneV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Update user
 */
export const UsersControllerUpdateV1Params = zod.object({
  "uuid": zod.string()
})

export const UsersControllerUpdateV1Body = zod.looseObject({

})

export const UsersControllerUpdateV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Soft delete user
 */
export const UsersControllerRemoveV1Params = zod.object({
  "uuid": zod.string()
})

export const UsersControllerRemoveV1Response = zod.void()

/**
 * @summary Update user status
 */
export const UsersControllerUpdateStatusV1Params = zod.object({
  "uuid": zod.string()
})

export const UsersControllerUpdateStatusV1Body = zod.object({
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING'])
})

export const UsersControllerUpdateStatusV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Replace user roles
 */
export const UsersControllerAssignRolesV1Params = zod.object({
  "uuid": zod.string()
})

export const UsersControllerAssignRolesV1Body = zod.object({
  "roleUuids": zod.array(zod.uuid()).describe('Role UUIDs to assign to the user')
})

export const UsersControllerAssignRolesV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Update user password
 */
export const usersControllerUpdatePasswordV1BodyNewPasswordMin = 8;



export const UsersControllerUpdatePasswordV1Body = zod.object({
  "currentPassword": zod.string(),
  "newPassword": zod.string().min(usersControllerUpdatePasswordV1BodyNewPasswordMin),
  "confirmNewPassword": zod.string()
})

export const UsersControllerUpdatePasswordV1Response = zod.void()

/**
 * @summary Upload the current user avatar
 */
export const UsersControllerUploadAvatarV1Body = zod.object({
  "file": zod.instanceof(File).optional()
})

export const UsersControllerUploadAvatarV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Upload a user avatar
 */
export const UsersControllerUploadUserAvatarV1Params = zod.object({
  "uuid": zod.string()
})

export const UsersControllerUploadUserAvatarV1Body = zod.object({
  "file": zod.instanceof(File).optional()
})

export const UsersControllerUploadUserAvatarV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "createdAt": zod.iso.datetime({"offset":true})
})

