/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Boilerplate API
 * API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Health check with dependency status
 */
export const HealthControllerCheckV1Response = zod.looseObject({

})

