FROM node:24-alpine AS dev

RUN corepack enable
WORKDIR /app

COPY --chown=node:node . .
RUN chown node:node /app

USER node

RUN corepack prepare --activate $(node -p "require('./package.json').packageManager")
RUN pnpm install

CMD ["sh", "-c", "pnpm --filter=@boilerplate/shared build && pnpm --filter=@boilerplate/api start:dev"]
