FROM node:24-alpine AS dev

RUN corepack enable
WORKDIR /app

COPY . .

RUN corepack prepare --activate $(node -p "require('./package.json').packageManager")
RUN pnpm install

USER node

CMD ["sh", "-c", "pnpm --filter=@boilerplate/shared build && pnpm --filter=@boilerplate/api start:dev"]
